{{- if .Values.cloudCore.featureGates.requireAuthorization }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcore-feature
  labels:
    rbac/aggregate-to-cloudcore: "true"
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["list", "watch"]
- apiGroups: ["policy.kubeedge.io"]
  resources: ["serviceaccountaccesses", "serviceaccountaccesses/status"]
  verbs: ["list", "watch", "create", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "clusterrolebindings", "rolebindings", "clusterroles"]
  verbs: ["list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kubelet-serving"]
  verbs: ["approve"]
{{- end }}
